In [ ]:
A = [ 1 1 0 3
      2 1 -1 1
      3 -1 -1 2
      -1 2 3 -1 ];
  
B = [ 4 ; 1; -3; 4 ];
X = [];
 
% Remove x1 from P2, P3 and P4
lambda = A(2,1) / A(1,1);
A(2,1) = A(2,1) - lambda * A(1,1);
A(2,2) = A(2,2) - lambda * A(1,2);
A(2,3) = A(2,3) - lambda * A(1,3);
A(2,4) = A(2,4) - lambda * A(1,4);
B(2) = B(2) - lambda * B(1);

lambda = A(3,1) / A(1,1);
A(3,1) = A(3,1) - lambda * A(1,1);
A(3,2) = A(3,2) - lambda * A(1,2);
A(3,3) = A(3,3) - lambda * A(1,3);
A(3,4) = A(3,4) - lambda * A(1,4);
B(3) = B(3) - lambda * B(1);

lambda = A(4,1) / A(1,1);
A(4,1) = A(4,1) - lambda * A(1,1);
A(4,2) = A(4,2) - lambda * A(1,2);
A(4,3) = A(4,3) - lambda * A(1,3);
A(4,4) = A(4,4) - lambda * A(1,4);
B(4) = B(4) - lambda * B(1);


% Removing x2 from P3 dan P4
lambda = A(3,2) / A(2,2);
% A(3,1) = A(3,1) - lambda * A(2,2);
A(3,2) = A(3,2) - lambda * A(2,2);
A(3,3) = A(3,3) - lambda * A(2,3);
A(3,4) = A(3,4) - lambda * A(2,4);
B(3) = B(3) - lambda * B(2);

lambda = A(4,2) / A(2,2);
A(4,1) = A(4,1) - lambda * A(2,2);
A(4,2) = A(4,2) - lambda * A(2,2);
A(4,3) = A(4,3) - lambda * A(2,3);
A(4,4) = A(4,4) - lambda * A(2,4);
B(4) = B(4) - lambda * B(2);

% Removing x3 from P4 (not mandatory in this case)
lambda = A(4,3) / A(3,3);
A(4,1) = A(4,1) - lambda * A(3,2);
A(4,2) = A(4,2) - lambda * A(3,2);
A(4,3) = A(4,3) - lambda * A(3,3);
A(4,4) = A(4,4) - lambda * A(3,4);
B(4) = B(4) - lambda * B(3);

% Reverse substitution
X(4) = B(4) / A(4,4);
X(3) = (B(3) - (A(3,4) * X(4))) / A(3,3);
X(2) = (B(2) - ((A(2,3) * X(3)) + (A(2,4) * X(4)))) / A(2,2);
X(1) = (B(1) - ((A(1,2) * X(2)) + (A(1,3) * X(3)) + (A(1,4) * X(4)))) / A(1,1);

A
B
X

In [32]:
A = [ 1 1 0 3
      2 1 -1 1
      3 -1 -1 2
      -1 2 3 -1 ];
  
B = [ 4 ; 1; -3; 4 ];
X = [];
 
% Remove x1 from P2, P3 and P4
dim = size(A);
m = dim(1);

for k = 1:m-1
    for i=k+1:m
        lambda = A(i,k) / A(k,k);
        for j = k:4
            A(i,j) = A(i,j) - lambda * A(k,j);
        end
        B(i) = B(i) - lambda * B(k);
    end
end

% Reverse substitution
X(m) = B(m) / A(m,m);

for i=m-1:-1:1
    sum = 0;
    for j = i+1:m
        sum = sum + (A(i,j) * X(j));
    end
    X(i) = (B(i) - sum) / A(i,i);
end

A
B
X


A =

     1     1     0     3
     0    -1    -1    -5
     0     0     3    13
     0     0     0   -13


B =

     4
    -7
    13
   -13


X =

    -1     2     0     1




In [41]:
A = [ 1 -1 2 -1
      2 -2 3 -3
      1 1 1 0
      1 -1 4 3 ];
  
B = [ 4 ; 1; -3; 4 ];
X = [];
 
% Remove x1 from P2, P3 and P4
dim = size(A);
m = dim(1);

for k = 1:m-1
    for i=k+1:m
        lambda = A(i,k) / A(k,k);
        for j = k:4
            A(i,j) = A(i,j) - lambda * A(k,j);
        end
        B(i) = B(i) - lambda * B(k);
    end
    % Check diagonal element, if it is 0, change with element beneath it
    s = 2;
    while A(k+1, k+1) == 0
        for p = 1:m
            temp = A(k+1, p);
            A(k+1, p) = A(k+s, p);
            A(k+s, p) = temp;
        end

        temp = B(k+1);
        B(k+1) = B(k+s);
        B(k+s) = temp;
        
        s = s + 1;
    end 
end

% Reverse substitution
X(m) = B(m) / A(m,m);

for i=m-1:-1:1
    sum = 0;
    for j = i+1:m
        sum = sum + (A(i,j) * X(j));
    end
    X(i) = (B(i) - sum) / A(i,i);
end

A
B
X


A =

     1    -1     2    -1
     0     2    -1     1
     0     0    -1    -1
     0     0     0     2


B =

     4
    -7
    -7
   -14


X =

   -24     7    14    -7




In [45]:
A = [ 1 -1 2 -1
      2 -2 3 -3
      1 1 1 0
      1 -1 4 3 ];
      
dim = size(B);
n = dim(2);
B = zeros(n);

for i = 1:n
    B(i,i) = 1;
end

X = [];
 
% Remove x1 from P2, P3 and P4
dim = size(A);
m = dim(1);

for k = 1:m-1
    for i=k+1:m
        lambda = A(i,k) / A(k,k);
        for j = k:4
            A(i,j) = A(i,j) - lambda * A(k,j);
        end
        
        for r = 1:n
            B(i,r) = B(i,r) - lambda * B(k,r);
        end
    end
    % Check diagonal element, if it is 0, change with element beneath it
    s = 2;
    while A(k+1, k+1) == 0
        for p = 1:m
            temp = A(k+1, p);
            A(k+1, p) = A(k+s, p);
            A(k+s, p) = temp;
        end
        
        for q = 1:m
            temp = B(q+1);
            B(q+1) = B(q+s);
            B(q+s) = temp;
        end
        s = s + 1;
    end 
end

% Reverse substitution
for r = 1:n
    X(m,r) = B(m,r) / A(m,m);
    for i=m-1:-1:1
        sum = 0;
        for j = i+1:m
            sum = sum + (A(i,j) * X(j));
        end
        X(i) = (B(i) - sum) / A(i,i);
    end
end

%A
B
%X


B =

     1     1     0     0
    -1    -2     0     0
    -1     0     1     0
    -2     0     2     1


